application: radiocicletta-static
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /
  static_files: assets/index.html
  upload: assets/index.html

- url: /
  static_dir: assets

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?ckeditor_src/.*
- ^(.*/)?ckeditor/_source/.*
- ^(.*/)?ckeditor/ckeditor\.pack
- ^(.*/)?ckeditor/.*\.html
- ^(.*/)?ckeditor/.*_source\.js
